Tip:
  symbol: GOLD
  type: SELL
  entry: 1861
  sl: 1871
  tps: [ 1857 ]
  volume: 1

Test:
  Assets:
    - symbol: BITCOIN
      volume: 0.1
      digits: 2
    - symbol: ETHEREUM
      volume: 1
      digits: 3
    - symbol: RIPPLE
      modify: 10
      volume: 1000
      digits: 4
    - symbol: LITECOIN
      volume: 10
      digits: 3

Update:
  type: 3
  entry: 1825.8
  sl: 1833.8
