Tip:
  symbol: GOLD
  type: SELL
  entry: 1861
  sl: 1871
  tps:
    - 1851
    - 1853
    - 1857
  volume: 0.01

Hedge:
  Assets:
    - symbol: BITCOIN
      volume: 0.1
      digits: 2
    - symbol: ETHEREUM
      volume: 1
      digits: 3
    - symbol: RIPPLE
      modify: 10
      volume: 1000
      digits: 4
    - symbol: LITECOIN
      volume: 10
      digits: 3

Update:
  type: 3
  entry: 1825.8
  sl: 1833.8

Xapi:
  accountId: 0
  password: ''

Telegram:
  token: ''
  apiId: 0
  apiHash: ''
  session: ''
  Chats: []
  ChatParserMap: {}
